CC=gcc
CFLAGS=-I/home/gfvante/hd/dev/c/c_lab/linked_list -I/home/gfvante/hd/dev/c/c_lab/utils

queuemake: queue_list.o ../../linked_list/linked_list.o
	$(CC) ../../linked_list/linked_list.o queue_list.o -o dynamic_queue
